# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute

# app_home:
#   path: /
#   controller: App\Controller\HomeController::index

teams:
    path: /
    controller: App\Controller\TeamsController::index

teams_add:
    path: /teams/add
    controller: App\Controller\TeamsController::add

players_buy_sell:
    path: /players/buy-sell
    controller: App\Controller\PlayersController::buySell